### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by phillipod** [quanah/net-ldapapi#14]
So the point raised in #13 regarding moving to version 3.1.x is interesting.

I'd like to see an 3.0.x API compatible release with recent bugfixes and enhancements, and ideally, I'd like the developer test suite I'm working on shipped with this release, so as to aid development during the API changes.

However, if API changes are possible within 3.1.x, it may be worth considering a few other things as well - such as providing emulated versions of ldap_url_search() for OpenLDAP, dropping functions not common across the target SDK's, or otherwise gracefully handling the lack of the ldap_url_search() methods (use of the LDAP_VENDOR_NAME and LDAP_NOT_SUPPORTED might do the trick here, in which case it could target 3.0.4).

I'll setup a couple of milestones on github, one targeting 3.0.4 and one targeting 3.1.0 to aid planning.

Will keep this ticket open till the release plan has been completed.

**Comment by phillipod** [comment]
Milestones for 3.0.4 and 3.1.0 have been created. Scheduling is currently arbitrary.

**Comment by phillipod** [comment]
I think we're pretty well ready to let this one fly once #36 is merged in, pending any testing.

**Comment by quanah** [comment]
Ok, still on my to-do to do some testing.  My work has been extremely busy. :/

**Comment by phillipod** [comment]
All good, I know what its like :)

**Comment by quanah** [comment]
Apparently something changed between OpenLDAP 2.4.40 and 2.4.42 that broke Net::LDAPapi's ability to function as a syncrepl change listener.  I'm currently investigating that issue.  I hope to have an example "listener" put into my ldap-tools repository soon, which could be used as a template for a basic test in the future.

**Comment by quanah** [comment]
Ok, I think we are good to release.  The issue with syncrepl I am unable to reproduce, and would be an openldap issue and not one with net::ldapapi either way.

**Comment by phillipod** [comment]
Hey,

Sounds good. Would you like me to prep a tar.gz for CPAN and send it to you?

Cheers,
Phillip

**Comment by quanah** [comment]
Sure, that'd be great!  And I guess lay down the appropriate tag?

**Comment by whm** [comment]
I was looking to pick up pushing the new release to debian testing through Russ Allbery.  Is there any one else picking doing this?

I also had some questions about the repo structure.  Will release versions be added to the branches directory.  Is that how releases are marked?

**Comment by phillipod** [comment]
@quanah Sorry for the delay - work is hectic as always. https://odonnell.net.nz/files/Net-LDAPapi-3.0.4.tar.gz - built against commit 91107fb60c36995e890785d541523e11233e4980 in my latest pull request (Updated MANIFEST file), which is based off accded0aaa4b2711c0bffdf6d0d4b727339d2737 (your update contact address commit)

I do have a separate branch with $VERSION in LDAPapi.pm updated to 3.0.4 (https://github.com/phillipod/net-ldapapi/tree/release-3.0.4) - I assume you want the release tag version to include this update but I'm not sure how to submit a pull request to a branch that doesn't exist in your tree :)

Happily, I have 6 weeks off work starting Tuesday and would definitely like to get 3.1 well underway during this time.

**Comment by phillipod** [comment]
@whm I figure since packages.debian.org shows you and Russ both as maintainers for the .deb, it'd make sense for you to grab this (which would be much appreciated, since I run lots of Debian systems!)

I'm not sure about the repository structure either - I think this git repo was a subversion import. I personally prefer the release tag / branch style, but I'll leave that up to @quanah, since it's his repository

**Comment by phillipod** [comment]
@quanah Sorry, forgot to mention:

```
$ md5sum Net-LDAPapi-3.0.4.tar.gz
aa887cde6a28ea647f3207bb07b1ac04  Net-LDAPapi-3.0.4.tar.gz
```

**Comment by quanah** [comment]
@phillipod Yeah, it was just pulled in via subversion from sourceforge, and hasn't had much done past that. ;)  Let me see what I can do about creating a different branch for 3.0.4

**Comment by quanah** [comment]
@phillipod Ok, I've cleaned up the repo and its structure. ;)

**Comment by quanah** [comment]
@phillipod you should be able to push me a merge now for the release-3.0.4 branch . ;)

**Comment by phillipod** [comment]
Done, and:

```
$ md5sum Net-LDAPapi-3.0.4.tar.gz
345446714d5cb9429a0009ed41db528f  Net-LDAPapi-3.0.4.tar.gz

```

https://odonnell.net.nz/files/Net-LDAPapi-3.0.4.tar.gz

**Comment by quanah** [comment]
Hm, this release stuff via github is a bit funky.  It created v3.0.4.tar.gz

**Comment by phillipod** [comment]
That is a bit funky. 

Differences are (net-ldapapi-3.0.4 = v3.0.4.tar.gz, Net-LDAPapi-3.0.4 = Net-LDAPapi-3.0.4.tar.gz) :

```
# diff -Bbur net-ldapapi-3.0.4 Net-LDAPapi-3.0.4
Only in net-ldapapi-3.0.4/examples: ldapwalk-dieter.pl
Only in net-ldapapi-3.0.4/examples: testurl.pl
Only in net-ldapapi-3.0.4: .gitignore
diff -Bbur net-ldapapi-3.0.4/MANIFEST Net-LDAPapi-3.0.4/MANIFEST
--- net-ldapapi-3.0.4/MANIFEST  2015-12-01 16:47:16.000000000 +1300
+++ Net-LDAPapi-3.0.4/MANIFEST  2015-12-01 16:01:58.000000000 +1300
@@ -45,3 +45,4 @@
 t/features/delete.feature
 t/01-bdd-cucumber.t
 t/test-config.pl
+META.json                                Module JSON meta-data (added by MakeMaker)
Only in Net-LDAPapi-3.0.4: META.json
Only in Net-LDAPapi-3.0.4: META.yml
Only in net-ldapapi-3.0.4: README.md
```

so it would certainly be my preference to have the 'make dist' output linked on the release page.

Looks like other files can be attached to the release via drag and drop, so maybe that will do it?

**Comment by phillipod** [comment]
_coughs_ Whoops. Monday is November 30th, not December 1st.

**Comment by quanah** [comment]
Yeah, will see if I can update the release with the bits generated by make dist, and just use that for future releases as well.

**Comment by quanah** [comment]
@phillipod ok updated with a new make dist with your latest changes. :)

**Comment by quanah** [comment]
Also updated CPAN.
