### ISSUE TITLE
debian build complains that compat level 4 no longer supported

### ISSUE THREAD

**Issue by macrotex** [quanah/net-ldapapi#38]
The debian build file debian/compat has the value 4. The pbuild process complains about 4 being too old and no longer supported. This was a build against jessie.

**Comment by quanah** [comment]
Thanks, we should remove the debian/ dir entirely, since upstream shouldn't have it.

**Comment by macrotex** [comment]
I just now looked at the changelog and that makes it clear that the included debian/ files should not be used. I will get the "official" Debian repo and use that instead for the build process.

**Comment by quanah** [comment]
Fixed with e2545b3af7181031a763e01009597233fcce9b39
