### ISSUE TITLE
is RPM package available for net-ldapapi in CENTOS/RHEL/ROCKYLinux repo's ?

### ISSUE THREAD

**Issue by umagmrit** [quanah/net-ldapapi#57]

**Comment by quanah** [comment]
Ask RedHat I suppose, or Fedora?

**Comment by umagmrit** [comment]
@quanah I am not able to find on RedHat/Centos repo's . Could you please share links to download net-ldapapi rpm's ?

**Comment by quanah** [comment]
This project only provides source.  If you need a pre-built RPM, you'll have to build the spec file yourself or ask the appropriate project to create one.

**Comment by umagmrit** [comment]
@quanah I am from zimbra org. We have a spec file created by you https://github.com/Zimbra/packages/blob/develop/thirdparty/perl-net-ldapapi/zimbra-perl-net-ldapapi/rpm/SPECS/net-ldapapi.spec, but we are planning to get all third-party packages from rhel/centos repositories instead of compiling ourselves all third-party packages.

**Comment by quanah** [comment]
Congratulations, you've partially discovered why Zimbra builds its own packages.  The path you're going down is an exceptionally bad idea for many reasons and is why builds weren't done this way.  But I'll leave it to your customers to discover the myriad reasons why it's a catastrophically bad idea when you do this.

**Comment by umagmrit** [comment]
@quanah small correction to my comment. I want to get all third-party packages from rhel/centos repositories except the packages we are patching like openldap, postfix, nginx, cyrus-sasl, etc... is it bad idea ? if we are not doing any customisation why can't we pull directly from os repo's ?

**Comment by robert-scheck** [comment]
> Ask RedHat I suppose, or Fedora?

I'm a Fedora and Fedora EPEL packager. As of writing, Net::LDAPapi is _not_ packaged for Fedora, and thus also neither part of CentOS Stream nor of RHEL (including RHEL clones like Rocky Linux). Given Red Hat determines the set of packages in CentOS Stream and RHEL (according to their discretion and preferences, and sometimes also according to their customer's preferences), a close way could be to package it for Fedora [EPEL](https://docs.fedoraproject.org/en-US/epel/epel-about/), which is however, strictly spoken, a third-party repository not enabled by default in CentOS Stream or RHEL. And keeping an RPM package in Fedora EPEL requires a package maintainer and ongoing maintenance efforts.
